### ISSUE TITLE
EmailFinisher option missing

### ISSUE THREAD

**Issue by iseries** [neos/form-builder#114]
E-Mail can't be send after submit a form because an exception was thrown. Some option for the EmailFinisher seems to be missing but all related properties for the Email Finisher content element were set correctly.

Installed `neos/neos 8.0.3`

**Reproduce**:
- Install `"neos/form-builder": "^2.3"` and `"neos/swiftmailer": "^7.3"` 
- Create a form with some form fields in the Neos Backend
- Add an E-Mail Finisher
- Set "Plaintext" for the "E-Mail Format" Property
- Go to the frontend, fill the form and submit
- Exception appears

**Exception**:
```
An exception was thrown while Neos tried to render your page

One of the option "templatePathAndFilename", "templateSource", "plaintextTemplatePathAndFilename", "plaintextTemplateSource", "htmlTemplatePathAndFilename", "htmlTemplateSource" must be set for the EmailFinisher.

root<Neos.Fusion:Case>/
 documentType<Neos.Fusion:Matcher>/
  element<Geopard.Mysite:Document.Homepage>/
   mainContent<Geopard.Mysite:Document.Fragment.Content.Main>/
    renderer<Neos.Neos:PrimaryContent>/
     default<Neos.Fusion:Matcher>/
      renderer<Neos.Neos:ContentCollection>/
       content<Neos.Neos:ContentCollectionRenderer>/
        itemRenderer<Neos.Neos:ContentCase>/
         default<Neos.Fusion:Matcher>/
          element<Geopard.FlexGrid:Content.Container>/
           renderer<Neos.Fusion:Tag>/
            content<Neos.Fusion:Tag>/
             content<Neos.Neos:ContentCollectionRenderer>/
              itemRenderer<Neos.Neos:ContentCase>/
               default<Neos.Fusion:Matcher>/
                element<Neos.Form.Builder:NodeBasedForm><Neos.Form.Builder:NodeBasedForm>/

For a full stacktrace, open Data/Logs/Exceptions/2022072709573821884d.txt
```

**Comment by bwaidelich** [comment]
@iseries Thanks for reporting, but (un)fortunately I can't reproduce the issue.
One thing you did not mention in the "reproduction" above is the actual configuration of the email body:
![image](https://user-images.githubusercontent.com/307571/181302610-040acef5-63db-446a-a0d3-d369616d5a29.png)
But I assume that you did that!?

**Comment by iseries** [comment]
oh man. yes, I didn't put any content here. After a text entry was made here, it also works for me. Sorry for your time looking into this...

**Comment by bwaidelich** [comment]
No problem, thanks for getting back :)
