### ISSUE TITLE
Using an identifier twice in the same form leads to an uncatched exception

### ISSUE THREAD

**Issue by DrillSergeant** [neos/form-builder#13]
**Steps to reproduce:**

1. insert a node based form
2. add an element (I used singleLineText) and specify an identifier (I used "name") and press "Apply"
3. add another element and specify the same identifier again and press "Apply"

**Expected result:**
I should not be able to apply my changes because the identifier is not unique (in this form)

**Actial result:**
The change is accepted and after reloading the page (which happens automatically) you end up with an exception while rendering the form-node.

If it is not possible to prevent to apply the change I would also be happy if
* a suffix would be appended to the identifier to make it unique
* the exception would be catched and a proper message would be delivered to the editor on the same spot where the form would be rendered ususally. Lilke "The identifier "name" is unsed more than once. Please make sure to use unique identifiers."

![image](https://user-images.githubusercontent.com/883552/33141406-5507f37a-cfb3-11e7-9d33-42a14f821c0c.png)

[20171122170819eca979.txt](https://github.com/neos/form-builder/files/1496977/20171122170819eca979.txt)

**Comment by DrillSergeant** [comment]
I am thinking about hiding the identifier-Field for the editor as they dont need to have speaking field-names. When rendering the mail in the mailfinisher we use the label to show the entered key-value pairs anyway.
But still I hope we can prevent this behaviour described in the issue.

**Comment by bwaidelich** [comment]
I think it makes sense to make the identifier editable by default because you can refer to it in the finisher options (e.g. `'replyToAddress' => '{email}', ...`).

Maybe we can validate the uniqueness of the identifier in the property editor already.. 
In any case we should catch Form exceptions in the backend
