### ISSUE TITLE
error while deactivating further pages

### ISSUE THREAD

**Issue by adrian-cerdeira** [neos/form-builder#135]
Hello 
When I want to deactivate (because I don't need it) `furtherPages` in yaml:
```
childNodes:
 'furtherPages': null
```
It gives me then this error:
<img width="455" alt="Bildschirmfoto 2024-07-02 um 13 48 03" src="https://github.com/neos/form-builder/assets/43271236/5dd29520-c67c-4c30-99e0-a6a3df8c8119">

When I check this in the line of code it breaks here, because `furtherPages` is null.
`  $output = $output . $this->wrapNode($node->getNode('furtherPages'), '', $fusionPath . '/furtherPages');`

Is it possible to make this a feature in the future?

**Comment by bwaidelich** [comment]
Thanks for reporting.
Would you be willing to create a PR that checks for that null case? That would greatly increase the chances for this feature to make it into the core :)

**Comment by bwaidelich** [comment]
You can just fork the repository, see https://docs.github.com/articles/creating-a-pull-request

**Comment by adrian-cerdeira** [comment]
@bwaidelich Thanks, PR is created.

**Comment by bwaidelich** [comment]
@adrian-cerdeira Thanks for your contribution, it's included in version [2.3.5](https://github.com/neos/form-builder/releases/tag/2.3.5)
