### ISSUE TITLE
Map E-Mail Body Text Variables

### ISSUE THREAD

**Issue by gradinarufelix** [neos/form-builder#15]
Hi,

I just spent two hours to find out, that when editing the e-mail text you can't use the variables like

`{message}`

like in all other fields. Instead you need to use something like

```
<f:for each="{form.formState.formValues}" as="value" key="label">
  {label}: {value}
</f:for>
```

It would be nice if we could map `{form.formState.formValues}` to the context by default.

Or any better ideas?

**Comment by bwaidelich** [comment]
The documentation has been extended with https://github.com/neos/form/pull/71
@gradinarufelix Some feedback would be nice.
Closing the ticket for now
