### ISSUE TITLE
Incomplete German translation

### ISSUE THREAD

**Issue by klfman** [neos/form-builder#23]
The form-builder does provide some German translation, especially in the property editor.

The NodeTypes, however, do not seem to be translated, so switching the neos backend to German still shows all the form-related NodeTypes in english:

![screen shot 2018-04-04 at 15 05 00](https://user-images.githubusercontent.com/9661367/38309359-2ae48e8a-381a-11e8-94c5-f4596457b55e.png)

Also, in the rendered output on the website the error hints are in English. I have no idea if Neos provides a way of translating that output, but the users of my customers site (which is in German) would probably expect german hints.

![screen shot 2018-04-04 at 15 08 24](https://user-images.githubusercontent.com/9661367/38309322-0f4b328c-381a-11e8-8252-593aac69492f.png)

**Comment by bwaidelich** [comment]
@klfman I just tested this and the translations work as expected.
They respect the locale that is active during *rendering* - Note that this doesn't have to be the same as the one configured for the Neos Backend user.

See https://neos.readthedocs.io/en/stable/HowTos/TranslatingContent.html and http://neos.readthedocs.io/en/stable/CreatingASite/ContentDimensions.html for more details.

Or, if you only have german content, try adding this to your `Settings.yaml`:
```yaml
Neos:
  Flow:
    i18n:
      defaultLocale: de
```
