### ISSUE TITLE
Undeclared dependency on neos-ui

### ISSUE THREAD

**Issue by kitsunet** [neos/form-builder#28]
This implementation

https://github.com/neos/form-builder/blob/703162d429142d8d48728107c985cb20f6f1dc12/Classes/NodeType/SelectOptionsCreationHandler.php#L5

creates an implicit dependency on the new UI package that is not declared in the composer.json, therefore any installation on a supported Neos version that hasn't go the new UI installed will lead to a fatal error. Either this dependency is declared or the class moved to a separate package.

**Comment by bweinzierl** [comment]
I ran into that problem with a minor project update in the Neos 3.2 branch. The formbuilder went from 1.0.0 to 1.0.4 and broke the installation. 
I suggest to remove this dependency or tag a new major version with the new dependency as this is a breaking change.

**Comment by lorenzulrich** [comment]
This situation also breaks usage of the Form Builder in Neos < 3.3 LTS. The Form Builder works fine without this class, but won't build with this error:

```
Exception: Required class "Neos\Neos\Ui\NodeCreationHandler\NodeCreationHandlerInterface" could not be loaded properly for reflection.

Possible reasons are:

 * Requiring non-existent classes
 * Using non-supported annotations
 * Class-/filename missmatch.

The "Neos.Flow.object.excludeClasses" setting can be used to skip classes from being reflected.
```

Since `excludeClasses` is deprecated, it would be good to have a working way of installing `Neos.FormBuilder` in < 3.3.

**Comment by lorenzulrich** [comment]
For those using composer-patches:

```
diff --git a/Classes/NodeType/SelectOptionsCreationHandler.php b/Classes/NodeType/SelectOptionsCreationHandler.php
deleted file mode 100644
index f5bad85..0000000
--- a/Classes/NodeType/SelectOptionsCreationHandler.php
+++ /dev/null
@@ -1,26 +0,0 @@
-<?php
-namespace Neos\Form\Builder\NodeType;
-
-use Neos\ContentRepository\Domain\Model\NodeInterface;
-use Neos\Neos\Ui\NodeCreationHandler\NodeCreationHandlerInterface;
-
-class SelectOptionsCreationHandler implements NodeCreationHandlerInterface
-{
-    /**
-     * @param NodeInterface $node The newly created node
-     * @param array $data incoming data from the creationDialog
-     * @return void
-     */
-    public function handle(NodeInterface $node, array $data)
-    {
-        if (!$node->getNodeType()->isOfType('Neos.Form.Builder:SelectOption')) {
-            return;
-        }
-        if (isset($data['value'])) {
-            $node->setProperty('value', $data['value']);
-        }
-        if (isset($data['label'])) {
-            $node->setProperty('label', $data['label']);
-        }
-    }
-}
```

```
  "extra": {
    "patches": {
      "neos/form-builder": {
        "BUGFIX: remove unsupported class": "patches/remove-select-options-creation-handler.patch"
      }
    }
  },
```
