### ISSUE TITLE
Issues with dynamic options and the site context variable

### ISSUE THREAD

**Issue by jobee** [neos/form-builder#40]
I try to implement dynamic options like https://github.com/neos/form-builder#dynamic-options
But for some reason the `site` context variable isn't always available and an `No operation which satisfies the runtime constraints found for "find".` exception is thrown from time to time.

Reproduceable steps (not sure about that right now):
It seems to be that on the first page request everything works fine.
On the second request (e.g. submit an invalid form or manually refresh via browser) the `site` var is gone.

Anyone seen this before and knows how to fix it?

Neos: 3.3.17
Form.Builder: 1.1.0

**Comment by daniellienert** [comment]
@jobee, experienced something similar, but didn't had the time to look int it yet, as it happens in very rare cases according to our monitoring. 

According to your description, it could be a problem with the missing context variable site in case the form is cached?

**Comment by jobee** [comment]
@daniellienert thanks for your response
my form should be uncached, as I inherit from the default `Neos.Form.Builder:Form`

I have multiple forms on the same document in this project, probably that has something to do with it?!

Will disable the other forms and report...

**Comment by jobee** [comment]
oh wait... I just realized that the default Form Fusion configuration is
```
prototype(Neos.Form.Builder:Form) {
    ...

    @cache {
        # By default Forms are not cached at all in order to avoid nasty bugs. If a form is "static" it should be cached for GET requests
        mode = 'uncached'
        context {
            # Fusion currently requires a context field to be specified for cache mode "uncached", but it's not actually needed here
            1 = 'none'
        }
    }
}
```

something like this seems to work for me
(ofc this depends on which context variables are needed within the form rendering, in my case I would also need `node` as I'm using `Neos.Neos:ConvertUris` ...)

```
prototype(Neos.Form.Builder:Form) {
    ...

    @cache {
        mode = 'uncached'
        context {
            1 = 'site'
            2 = 'node'
        }
    }
}
```
what are the possible drawbacks with extending `@cache.context` or why is it set to `1 = 'node'` by default?

**Comment by bwaidelich** [comment]
> what are the possible drawbacks with extending `@cache.context`

There are no real drawbacks other than more dependencies that might not be needed. Because we can't know which context variables you depend on the idea is that you just add custom caching in your own implementation. See https://github.com/neos/form-builder#caching for example
