### ISSUE TITLE
Copy a form element with an identifier set leads to an exception and breaks future editing

### ISSUE THREAD

**Issue by paavo** [neos/form-builder#44]
### Description

[Description of the bug or feature]
If i copy and paste a form-element with an identifier (ex: budget) set, i get the exception `A form element with identifier "budget" is already part of the form` which seems legit…
BUT im not able to edit the form because the exception “breaks” the Content Tree..

![image](https://user-images.githubusercontent.com/1118783/61111645-57621a80-a48a-11e9-861d-9a058a2f8948.png)

### Steps to Reproduce

1. Add a Form Element
2. Set an Identifier
3. Copy the Element
4. Paste the Element
5. Exception 💥

#### Expected behavior
There are many options, maybe a Modal where u have to set a new identifier (like page creation) or same as in the uriPathSegment where `-1` is added to the identifier?

### Affected Versions
Neos: 4.3

**Comment by bwaidelich** [comment]
Thanks for reporting and thanks for fixing!
#72 will be included in the next Bugfix release
