### ISSUE TITLE
SwiftMailer error on sending attachments with the E-Mail Finisher

### ISSUE THREAD

**Issue by dba96** [neos/form-builder#49]
If I use the new neos/swiftmailer package (^6) and try to send attachments via the e-mail finisher you get the following error: 
`Call to undefined method Swift_Attachment::newInstance()`

From the error, it's clear that Swift_SmtpTransport class doesn't have a newInstance method.

**Comment by bwaidelich** [comment]
Thanks for reporting this, but this would be an issue of the forms package (https://github.com/neos/form)

**Comment by bwaidelich** [comment]
I moved the issue => https://github.com/neos/form/issues/112
