### ISSUE TITLE
Problem with E-Mail validator

### ISSUE THREAD

**Issue by patriceckhart** [neos/form-builder#64]
When I insert an email validator, I get the error: Neos 5.1, form-builder: 2.0.0

`Return value of Neos\Form\Builder\Fusion\ValidatorImplementation_Original::getOptions() must be of the type array, null returned`

**Comment by EnesE** [comment]
Same issue with the Image-Upload

`
Return value of Neos\Form\ViewHelpers\Form\UploadedImageViewHelper_Original::getUploadedImage() must be an instance of Neos\Media\Domain\Model\Image, null returned - Check the logs for details
`

Neos 5.1.2
Form-Builder: 2.0.0

**Comment by bwaidelich** [comment]
@patriceckhart I can't reproduce this issue (and it's not related to the issue @EnesE mentioned). Did you change the Neos Form fusion code and/or settings?

**Comment by patriceckhart** [comment]
> @patriceckhart I can't reproduce this issue (and it's not related to the issue @EnesE mentioned). Did you change the Neos Form fusion code and/or settings?

At some point I overwritten the validator (Fusion). That caused the mistake. Thank you. I no longer remembered it.

**Comment by bwaidelich** [comment]
OK, thanks for the update
