### ISSUE TITLE
Problem with Image Upload

### ISSUE THREAD

**Issue by EnesE** [neos/form-builder#65]
When I insert an Image-Upload, I get the error message:

`Return value of Neos\Form\ViewHelpers\Form\UploadedImageViewHelper_Original::getUploadedImage() must be an instance of Neos\Media\Domain\Model\Image, null returned - Check the logs for details`

Neos 5.1.2
Form-Builder: 2.0.0

**Comment by bwaidelich** [comment]
This was a recent regression. I'll fix it via https://github.com/neos/form/issues/118
