### ISSUE TITLE
Exporting and re-importing empty labels gives an error

### ISSUE THREAD

**Issue by zickgraf** [neos/form-builder#70]
If you have form elements with empty labels, exporting the site and re-importing it gives the following error when rendering the form:
```
Return value of Neos\Form\ViewHelpers\TranslateElementPropertyViewHelper_Original::render() must be of the type string, null returned
Exception Code	0
Exception Type	TypeError
Thrown in File	Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Form_ViewHelpers_TranslateElementPropertyViewHelper.php
Line	83
Original File	Packages/Application/Neos.Form/Classes/ViewHelpers/TranslateElementPropertyViewHelper.php
```

#### Steps to reproduce:
1. Create a form
2. Create a "Single-line text" form element
3. Set the label to the empty string
4. Apply, publish, and export the site to Sites.xml
5. Prune the site and make a new import from Sites.xml
6. Try to access the form

#### Actual result:
The error mentioned above occurs.

#### Expected result:
The form displays without an error.

#### Versions:
* neos/neos: 5.2.1
* neos/form-builder: 2.0.0

**Comment by zickgraf** [comment]
I can confirm that the linked commit fixes the bug, thanks!

**Comment by bwaidelich** [comment]
> I can confirm that the linked commit fixes the bug

Thanks for the feedback. The fix is now released in all supported branches
