### ISSUE TITLE
Adding options does not refresh the UI

### ISSUE THREAD

**Issue by DrillSergeant** [neos/form-builder#8]
Steps to reproduce:
* Add a form
* Insert an element that has options (like a Dropdown)
* Add an option

Expected result:
The option is visible in the UI and ready to be modified (value, identifier, ...)

Actual result:
After adding the option it does not appear in the UI. You need to refresh the structure-tree, locate the new option manually and click it to be able to modify it.

Tested in the new UI but I am quite sure it also happens in the old UI.

**Comment by bwaidelich** [comment]
Fixed with Neos 3.3.9
